version: '3.8'

services:
  chatbot-app:
    build: .
    ports:
      - "5000:5000"  # Backend API
      - "8000:8000"  # Frontend
    volumes:
      - ./ecommerce-dataset:/app/ecommerce-dataset
    environment:
      - FLASK_ENV=production
      - FLASK_APP=backend/app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 